const Menu = [
{
    id:1,
    Image: "image/image_1.jpg",
    name: "food_1",
    category: "Lunch",
    price: "$24",
    description:
      " Food is any substance consumed by an organism for nutritional support. Food is usually of plant, animal, or fungal origin, and contains essential nutrients, such as carbohydrates, fats, proteins, vitamins, or minerals "
},
{
    id:2,
    Image: "image/image_2.jpg",
    name: "food_2",
    category: "Lunch",
    price: "$25",
    description: " The substance is ingested by an organism and assimilated by the organism's cells to provide energy, maintain life, or stimulate growth. Different species of animals have different feeding behaviours that satisfy the needs of their unique metabolisms, often evolved to fill a specific ecological niche within specific geographical contexts",
},
{
    id:3,
    Image: "image/image_3.jpg",
    name: "food_3",
    category: "Lunch",
    price: "$26",
    description: "Omnivorous humans are highly adaptable and have adapted to obtain food in many different ecosystems. The majority of the food energy required is supplied by the industrial food industry, which produces food with intensive agriculture and distributes it through complex food processing and food distribution systems",
},
{
    id:4,
    Image: "image/image_4.jpg",
    name: "food_4",
    category: "Breakfast",
    price: "$21",
    description: " This system of conventional agriculture relies heavily on fossil fuels, which means that the food and agricultural system is one of the major contributors to climate change, accountable for as much as 37% of total greenhouse gas emissions.[1]",
},
{
    id:5,
    Image: "image/image_5.jpg",
    name: "food_5",
    category: "Breakfast",
    price: "$22",
    description: "The food system has significant impacts on a wide range of other social and political issues including: sustainability, biological diversity, economics, population growth, water supply, and access to food. Food safety and food security are monitored by international agencies like the International Association for Food Protection, World Resources Institute, World Food Programme, Food and Agriculture Organization, and International Food Information Council",
},
{
    id:6,
    Image: "image/image_6.jpg",
    name: "food_6",
    category: "Breakfast",
    price: "$23",
    description: "Food is any substance consumed to provide nutritional support and energy to an organism.[2][3] It can be raw, processed or formulated and is consumed orally by animals for growth, health or pleasure. Food is mainly composed of water, lipids, proteins and carbohydrates. Minerals (e.g. salts) and organic substances (e.g. vitamins) can also be found in food",
},
{
    id:7,
    Image: "image/image_7.jpg",
    name: "food_7",
    category: "Dinner",
    price: "$27",
    description: " Plants, algae and some microorganisms use photosynthesis to make their own food molecules.[5] Water is found in many foods and has been defined as a food by itself.[6] Water and fiber have low energy densities, or calories, while fat is the most energy dense component.[3] Some inorganic (non-food) elements are also essential for plant and animal functioning",
},
{
    id:8,
    Image: "image/image_8.jpg",
    name: "food_8",
    category: "Dinner",
    price: "$28",
    description: "Human food can be classified in various ways, either by related content or by how the food is processed.[8] The number and composition of food groups can vary. Most systems include four basic groups that describe their origin and relative nutritional function",
},
{
    id:9,
    Image: "image/image_9.jpg",
    name: "food_9",
    category: "Dinner",
    price: "$29",
    description: " Vegetables and Fruit, Cereals and Bread, Dairy, and Meat.[9] Studies that look into diet quality often group food into whole grains/cereals, refined grains/cereals, vegetables, fruits, nuts, legumes, eggs, dairy products, fish, red meat, processed meat, and sugar-sweetened beverages",
},
{
    id:10,
    Image: "image/image_10.jpg",
    name: "food_10",
    category: "Evening",
    price: "$30",
    description: "The Food and Agriculture Organization and World Health Organization use a system with nineteen food classifications: cereals, roots, pulses and nuts, milk, eggs, fish and shellfish, meat, insects, vegetables, fruits, fats and oils, sweets and sugars, spices and condiments, beverages, foods for nutritional uses, food additives, composite dishes and savoury snacks.[13]",
},
];

export default Menu;